### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by max133** [log0/neural-style-painting#4]
When i start art.py i get this error:

> python art.py
> 
> art.py:147: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future 
> will perform elementwise comparison
>   assert layer_name == expected_layer_name
> Traceback (most recent call last):
>   File "art.py", line 277, in <module>
>     model = load_vgg_model(VGG_MODEL)
>   File "art.py", line 184, in load_vgg_model
>     graph['conv1_1']  = _conv2d_relu(graph['input'], 0, 'conv1_1')
>   File "art.py", line 173, in _conv2d_relu
>     return _relu(_conv2d(prev_layer, layer, layer_name))
>   File "art.py", line 162, in _conv2d
>     W, b = _weights(layer, layer_name)
>   File "art.py", line 147, in _weights
>     assert layer_name == expected_layer_name
> AssertionError

How to fix it?

Thank you

**Comment by ghost** [comment]
your solution is here: https://github.com/log0/neural-style-painting/issues/2
